@startuml

title __CONNECTION's Class Diagram__\n

  namespace connection {
    class connection.DAOTest {
    }
  }
  

  namespace connection {
    class connection.DBConnect {
        {static} + DBName : String
        {static} - DB_DRIVER : String
        {static} - DB_PASSWORD : String
        {static} - DB_URL : String
        {static} - DB_USER : String
        + createQuestions()
        {static} + dbExecuteQuery()
        {static} + dbExecuteUpdate()
        {static} - getDBConnection()
    }
  }
  

  namespace connection {
    class connection.DBConnect.nameColAnswers {
        {static} + ANSWER : String
        {static} + ID : String
        {static} + TYPE : String
    }
  }
  

  namespace connection {
    class connection.DBConnect.nameColQuestions {
        {static} + ID : String
        {static} + QUESTION : String
    }
  }
  

  namespace connection {
    class connection.DBConnect.nameColQuestions_Answers {
        {static} + ID : String
        {static} + ID_ANSWER : String
        {static} + ID_QUESTION : String
    }
  }
  

  namespace connection {
    class connection.DBConnect.nameColTables {
        {static} + ANSWERS : String
        {static} + QUESTIONS : String
        {static} + QUESTIONS_ANSWERS : String
    }
  }
  

  connection.DBConnect +-down- connection.DBConnect.nameColAnswers
  connection.DBConnect +-down- connection.DBConnect.nameColQuestions
  connection.DBConnect +-down- connection.DBConnect.nameColQuestions_Answers
  connection.DBConnect +-down- connection.DBConnect.nameColTables


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
